# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cperson.proto\"3\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x0f\n\x07married\x18\x03 \x01(\x08\"\"\n\x12RequestInforPerson\x12\x0c\n\x04name\x18\x01 \x01(\t\")\n\x19RequestCheckMaritalStatus\x12\x0c\n\x04name\x18\x01 \x01(\t\"*\n\x17RespondGetMaritalStatus\x12\x0f\n\x07married\x18\x01 \x01(\x08\x32\x83\x01\n\rAsillaService\x12*\n\x08getInfor\x12\x13.RequestInforPerson\x1a\x07.Person\"\x00\x12\x46\n\x0c\x63heckMarried\x12\x1a.RequestCheckMaritalStatus\x1a\x18.RespondGetMaritalStatus\"\x00\x62\x06proto3')



_PERSON = DESCRIPTOR.message_types_by_name['Person']
_REQUESTINFORPERSON = DESCRIPTOR.message_types_by_name['RequestInforPerson']
_REQUESTCHECKMARITALSTATUS = DESCRIPTOR.message_types_by_name['RequestCheckMaritalStatus']
_RESPONDGETMARITALSTATUS = DESCRIPTOR.message_types_by_name['RespondGetMaritalStatus']
Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), {
  'DESCRIPTOR' : _PERSON,
  '__module__' : 'person_pb2'
  # @@protoc_insertion_point(class_scope:Person)
  })
_sym_db.RegisterMessage(Person)

RequestInforPerson = _reflection.GeneratedProtocolMessageType('RequestInforPerson', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTINFORPERSON,
  '__module__' : 'person_pb2'
  # @@protoc_insertion_point(class_scope:RequestInforPerson)
  })
_sym_db.RegisterMessage(RequestInforPerson)

RequestCheckMaritalStatus = _reflection.GeneratedProtocolMessageType('RequestCheckMaritalStatus', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTCHECKMARITALSTATUS,
  '__module__' : 'person_pb2'
  # @@protoc_insertion_point(class_scope:RequestCheckMaritalStatus)
  })
_sym_db.RegisterMessage(RequestCheckMaritalStatus)

RespondGetMaritalStatus = _reflection.GeneratedProtocolMessageType('RespondGetMaritalStatus', (_message.Message,), {
  'DESCRIPTOR' : _RESPONDGETMARITALSTATUS,
  '__module__' : 'person_pb2'
  # @@protoc_insertion_point(class_scope:RespondGetMaritalStatus)
  })
_sym_db.RegisterMessage(RespondGetMaritalStatus)

_ASILLASERVICE = DESCRIPTOR.services_by_name['AsillaService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERSON._serialized_start=16
  _PERSON._serialized_end=67
  _REQUESTINFORPERSON._serialized_start=69
  _REQUESTINFORPERSON._serialized_end=103
  _REQUESTCHECKMARITALSTATUS._serialized_start=105
  _REQUESTCHECKMARITALSTATUS._serialized_end=146
  _RESPONDGETMARITALSTATUS._serialized_start=148
  _RESPONDGETMARITALSTATUS._serialized_end=190
  _ASILLASERVICE._serialized_start=193
  _ASILLASERVICE._serialized_end=324
# @@protoc_insertion_point(module_scope)
