# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import person_pb2 as person__pb2


class AsillaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getInfor = channel.unary_unary(
                '/AsillaService/getInfor',
                request_serializer=person__pb2.RequestInforPerson.SerializeToString,
                response_deserializer=person__pb2.Person.FromString,
                )
        self.checkMarried = channel.unary_unary(
                '/AsillaService/checkMarried',
                request_serializer=person__pb2.RequestCheckMaritalStatus.SerializeToString,
                response_deserializer=person__pb2.RespondGetMaritalStatus.FromString,
                )


class AsillaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getInfor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def checkMarried(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AsillaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getInfor': grpc.unary_unary_rpc_method_handler(
                    servicer.getInfor,
                    request_deserializer=person__pb2.RequestInforPerson.FromString,
                    response_serializer=person__pb2.Person.SerializeToString,
            ),
            'checkMarried': grpc.unary_unary_rpc_method_handler(
                    servicer.checkMarried,
                    request_deserializer=person__pb2.RequestCheckMaritalStatus.FromString,
                    response_serializer=person__pb2.RespondGetMaritalStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AsillaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AsillaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getInfor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AsillaService/getInfor',
            person__pb2.RequestInforPerson.SerializeToString,
            person__pb2.Person.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def checkMarried(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AsillaService/checkMarried',
            person__pb2.RequestCheckMaritalStatus.SerializeToString,
            person__pb2.RespondGetMaritalStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
